services:
  - docker

language: go
go:
  - 1.8.x

branches:
  only:
    - master
    - /^bzub-.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

install:
  # TODO: Make the "1.7" based on $KUBE_VERSION
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable-1.7.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl

env:
  global:
    - REPO=cloudnativelabs/kube-router
    - REPO_PATH=$HOME/gopath/src/github.com/$REPO
    - GIT_BRANCH=$TRAVIS_BRANCH
  matrix:
    # - KUBE_VERSION=v1.6
    - KUBE_VERSION=v1.7

before_script:
  - make test
  - make _cache/kube-metal/assets/auth/kubeconfig # terraform apply

script:
  - travis_wait make test-e2e E2E_FOCUS="Conformance" E2E_SKIP="Disruptive|Kubectl"
  - travis_wait make test-e2e E2E_FOCUS="Networking" E2E_SKIP="Disruptive|Kubectl|Conformance"
  - travis_wait make test-e2e E2E_FOCUS="Network" E2E_SKIP="Disruptive|Kubectl|Conformance|Networking"
  - travis_wait make test-e2e E2E_FOCUS="Feature:NetworkPolicy" E2E_SKIP="Disruptive|Kubectl|Conformance|Networking|Network"
  - travis_wait make test-e2e E2E_FOCUS="Feature:NoSNAT" E2E_SKIP="Disruptive|Kubectl|Conformance|Networking|Network|Feature:NetworkPolicy"
  # - travis_wait make test-e2e E2E_FOCUS="Network.*" E2E_SKIP="Kubectl|Conformance|Networking|Network|Feature:NetworkPolicy"
  - make tf-destroy

after_failure:
  - make tf-destroy

# All successfully built commits get an image placed in the kube-router-git
# image repo and tagged with the commit hash.
deploy:
  provider: script
  script: build/travis-deploy.sh

# This fixes issues when a contributor uses their own Travis CI account to test
# code/CI changes.
before_install:
  - mkdir -p $REPO_PATH
  - rsync -az ${TRAVIS_BUILD_DIR}/ $REPO_PATH
  - export TRAVIS_BUILD_DIR=$REPO_PATH
  - cd $REPO_PATH
