services:
  - docker

language: go
go:
  - 1.8.x

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

cache:
  directories:
    - _cache

env:
  global:
    - REPO=cloudnativelabs/kube-router
    - REPO_PATH=$HOME/gopath/src/github.com/$REPO
    - GIT_BRANCH=$TRAVIS_BRANCH
    - PACKET_FACILITY=nrt1
    - SPOT_INSTANCE="true"
    - SPOT_PRICE_MAX=".01"
    - 'E2E_SKIP_COMMON=(?i)\[k8s.io\] (Kubectl)|\[Disruptive\]|\[Experimental\]|\[HPA\]|should check kube-proxy urls|should set TCP CLOSE_WAIT timeout|should be able to create a functioning NodePort service|should update endpoints: (http|udp)|should function for (node-Service|endpoint-Service|pod-Service): (http|udp)|should update nodePort: (http|udp) \[Slow\]'
  matrix:
    # TODO: support testing against different k8s versions
    # - KUBE_VERSION=v1.6
    - KUBE_VERSION=v1.7

jobs:
  include:
    - stage: e2e-setup
      script: make _cache/kube-metal/assets/auth/kubeconfig
    # - stage: e2e-run
    #   script: ls -l _cache/kube-metal
    # - script: ls -l _cache/kube-metal/assets/auth/kubeconfig
    # - stage: deploy
    #   provider: script
    #   script: build/travis-deploy.sh

# before_script:
#   - make test

# after_failure:
#   - make tf-destroy

# after_success:
#   - make tf-destroy

# This fixes issues when a contributor uses their own Travis CI account to test
# code/CI changes.
before_install:
  - mkdir -p $REPO_PATH
  - rsync -az ${TRAVIS_BUILD_DIR}/ $REPO_PATH
  - export TRAVIS_BUILD_DIR=$REPO_PATH
  - cd $REPO_PATH
