services:
  - docker

language: go
go:
  - 1.8.x

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

env:
  global:
    - REPO=cloudnativelabs/kube-router
    - REPO_PATH=$HOME/gopath/src/github.com/$REPO
    - GIT_BRANCH=$TRAVIS_BRANCH
    - PACKET_FACILITY=nrt1
    - SPOT_INSTANCE="true"
    - SPOT_PRICE_MAX=".01"
    - E2E_SKIP_COMMON="Disruptive|Kubectl|Experimental"
  matrix:
    # TODO: support testing against different k8s versions
    # - KUBE_VERSION=v1.6
    - KUBE_VERSION=v1.7

before_script:
  - make test

script:
  - echo "Starting test cluster"
  - make _cache/kube-metal/assets/auth/kubeconfig # terraform apply
  - cat _cache/hosts
  - echo "Starting e2e test [Feature:NetworkPolicy]"
  - cat _cache/hosts
  - make test-e2e E2E_FOCUS="Feature:NetworkPolicy" E2E_SKIP="${E2E_SKIP_COMMON}"
  - echo "Starting e2e test [Conformance]"
  - cat _cache/hosts
  - make test-e2e E2E_FOCUS="Conformance" E2E_SKIP="${E2E_SKIP_COMMON}Feature:NetworkPolicy"
  #
  # - make test-e2e E2E_FOCUS="Networking" E2E_SKIP="${E2E_SKIP_COMMON}"
  # - make test-e2e E2E_FOCUS="Network" E2E_SKIP="${E2E_SKIP_COMMON}|Networking"
  # - make test-e2e E2E_FOCUS="Feature:NetworkPolicy" E2E_SKIP="${E2E_SKIP_COMMON}|Networking|Network"
  # - make test-e2e E2E_FOCUS="Feature:NoSNAT" E2E_SKIP="${E2E_SKIP_COMMON}|Networking|Network|Feature:NetworkPolicy"
  # - make test-e2e E2E_FOCUS="Conformance" E2E_SKIP="${E2E_SKIP_COMMON}|Networking|Network|Feature:NetworkPolicy|Feature:NoSNAT"

after_failure:
  - make tf-destroy

after_success:
  - make tf-destroy

# All successfully built commits get an image placed in the kube-router-git
# image repo and tagged with the commit hash.
deploy:
  provider: script
  script: build/travis-deploy.sh

# This fixes issues when a contributor uses their own Travis CI account to test
# code/CI changes.
before_install:
  - mkdir -p $REPO_PATH
  - rsync -az ${TRAVIS_BUILD_DIR}/ $REPO_PATH
  - export TRAVIS_BUILD_DIR=$REPO_PATH
  - cd $REPO_PATH
